In [4]:
import numpy

In [8]:
a = numpy.arange(18).reshape(6,3)

In [12]:
print a

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [14]:
print a.reshape(2,3,3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
